### ISSUE TITLE
[Feature] Add Terraform Modules

### ISSUE THREAD

**Issue by johandry** [johandry/terranova#16]
**Is your feature request related to a problem? Please describe.**
The Local Terraform Modules are not supported in Terranova because the Terraform code is stored in a single file before process it. Would be great to have local modules in Terranova.

**Describe the solution you'd like**
Implement the `AddModule(name, code)` method to support terraform local modules.

**Describe alternatives you've considered**
It's possible to have remote modules. It's also possible to have part of the Terraform code in a different Go variable and append it to the main Terraform code, like this:
```
alb := `resource "aws_elb" "my_alb" { ... }`
vpc := `resource "aws_vpc" "my_vpc" { ... }`
main := `provider "aws" { ... }`
p := terranova.NewPlatform(main + alb + vpc)
```

**Proposal**
In the `config()` method - check [here](https://github.com/johandry/terranova/blob/master/terranova.go#L121) - the Terraform code is stored in a file in a temporal directory. This same location can be used to create a directory for every Terraform module so the developer can load such modules with:
```
module "webserver” {  
  source = “./webserver”
  name  = "stage”
}
```

The develper has to load the module like this:
```
p := terranova.NewPlatform(main_code).AddModule("webserver", module_code)
```

**Additional context**

**References**
I'd like to thank to [Gianluca Natali](https://github.com/gianlucanatali) to for the interest in using Terraform Local Modules with Terranova.

**Comment by sonnysideup** [comment]
How exactly would this work in practice?

**Comment by johandry** [comment]
Using the method `AddFile(filename, code string)`. You need to walk thru all the files in the terraform code directory and add them to the platform. However, the idea of terranova is not to have TF code in a directory, otherwise terraform may be a better option. The idea is to have your code embedded in your program or generated at execution time.

If there is a file or TF code in `production/webserver.tf` add it as `p.AddFile("production/webserver.tf", fileContent)`.

I think an example would be better to explain this, I'll work on it and share it in the `terranova-examples` repository.

**Comment by jasmingacic** [comment]
@johandry what about that example you mentioned above? Also is Terranova able to initialize backends?
