### ISSUE TITLE
[Feature] Create testing files

### ISSUE THREAD

**Issue by johandry** [johandry/terranova#5]
**Description**

The current version do not have any unit testing files. It's required before implementing CI/CD and critical to ensure the quality of the package. As we add more features more difficult will be to verify the quality and stability of the package.

It's important to create, at least, the files `platform_test.go` and `terranova_test.go`. It may be nice to have an `example.go` file that can be used also to embed in the documentation.

**Describe the results you received:**

No test neither results from `go test .`

**Describe the results you expected:**

Expected some test and test results when `go test .` is executed.

**Additional information you deem important (e.g. issue happens only occasionally):**

Recommended to verify how Hashicorp do testing to the implemented functions and try to make similar tests.

**Terranova version:** v0.0.0

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by KaushikIyer16** [comment]
hey can i help you on this

**Comment by johandry** [comment]
Absolutely! 
Let me know which components you would like to do the unit test.
Thanks Kaushik!

**Comment by KaushikIyer16** [comment]
can you provide me of some documentation, and then ill be able to help you out in a structured manner. Thank you so much for letting me help you on this, i personally like the applications of this library
